### PR TITLE
Simplified/shortened the error and NodeList function

### PR DESCRIPTION
**Pull request by qw3n**
Like the library thought this would shorten the code just a bit.

### CODE REVIEW

**Comment by eorroe** [comment]
As far as the `nodeError` since the minified version is not smart enough to save it to a variable since I've used the same error, I'll do that.

However one thing about that, as you'll see in the change I make, next time just set the `nodesError` right where you declared it, at the top.

However your `NodeList` constructor function does not work properly here's why:

``` JS
function NodeList( args ) {
    var i, l, list=args.length;
    if(typeof args[0] === 'string'){
        list=( args[1] || document ).querySelectorAll( args[0] );
    } else if( 0 in args && !( args[0] instanceof Node ) && 'length' in args[0] ) {
        list=args[ 0 ];
        if( args[1] ) this.owner = args[1];
    }
    for( i = 0, l = this.length = list.length; i < l; i++ ) this[ i ] = list[ i ];
 }
```
1. `list=args.length` is not what you want, `args.length` will give you a number, so trying to do `list.length` is trying to get the length of a number.
2. What you were trying to do by defining the variable there is actually `list = args` so that I don't need the last else statement
3. No need to change the variable name to `list`, I'll still be using `nodes` to keep it consistent to the rest of the file, you should be using the minified version anyways
4. Here's the fix:

``` JS
function NodeList( args ) {
    var i = 0, l, list = args;
    if(typeof args[0] === 'string') {
        list = ( args[1] || document ).querySelectorAll( args[0] );
    } else if( 0 in args && !( args[0] instanceof Node ) && 'length' in args[0] ) {
        list = args[ 0 ];
        if( args[1] ) this.owner = args[1];
    }
    for( l = this.length = list.length; i < l; i++ ) this[ i ] = list[ i ];
}
```

**So thanks, all I've been working on so far as you can see with the recent change is small optimizations like this.**

The one for loop is a big win, I've been doing seperate for loops in other functions like in the `set()` method because its faster to have seperate for loops, than to keep checking each time you loop for something that will always return `null` (If you don't understand that part let me know if you'd like me to explain, but AFAIK that one is optimized already) so the `NodeList` function constructor I did a seperate for loop without even thinking about it, since I did it after that `set()` method.

So since I'll be making the change right now, you can pretty much delete this branch, simply because I'll be doing the change right now so I don't have to fork my own project, I think that's pretty dumb that github makes you do that.

If you see more optimizations I can do, please let me know thanks again.

**Comment by qw3n** [comment]
I corrected the list=args.length earlier but somehow it didn't make it into the version I committed. Also, the changed variable name is an artifact of originally leaving the nodes variable in place. I later realized it wasn't necessary and took it out and directly assigned the (args[1... to list.

**Comment by eorroe** [comment]
Not sure what you mean by

> I later realized it wasn't necessary and took it out and directly assigned the (args[1... to list.

also their is one more thing I could do to make it shorter:

``` JS
function NodeList( args ) {
    var i = 0, l;
    if(typeof args[0] === 'string') {
        args = ( args[1] || document ).querySelectorAll( args[0] );
    } else if( 0 in args && !( args[0] instanceof Node ) && 'length' in args[0] ) {
        if( args[1] ) this.owner = args[1];
        args = args[ 0 ];
    }
    for( l = this.length = args.length; i < l; i++ ) this[ i ] = args[ i ];
}
```

but I won't do that because its not too clear, if someone is trying to look at the source code it could be confusing. It'll kill a couple bytes off but not worth it.

**Comment by qw3n** [comment]
I originally had 

``` javascript
nodes = ( args[1] || document ).querySelectorAll( args[0] );
list=nodes;
```

but then I just changed it to

``` javascript
list = ( args[1] || document ).querySelectorAll( args[0] );
```

Basically that's why i created the new variable list.

**Comment by eorroe** [comment]
The methods should have names, debugging purposes.

and `$$.name === 'NodeListJS' // true` because if someone types out `$$` into the console they'll know that `NodeListJS` is being used instead of the CommandLineAPI default `$$` method or any other library that overrides `$$`

**Pull request closed without merging**
